### Create new user
POST http://localhost:3333/api/auth/signup
content-type: application/json

{
    "username": "knight",
    "email": "knight.sarai.dev@gmail.com",
    "password": "1234455."
}

### Signin
POST http://localhost:3333/api/auth/signin
content-type: application/json

{
    "email": "knight.sarai.dev@gmail.com",
    "password": "1234455."
}

### Signout
POST http://localhost:3333/api/auth/signout
content-type: application/json

{
    "email": "knight.sarai.dev2@gmail.com",
    "password": "1234455."
}
 
### Get User
GET http://localhost:3333/api/auth/me

